### PR TITLE
Use the vim, not a shell to find the node_modules

### PR DESCRIPTION
**Pull request by shofel**
The impetus for this commit is improving performance and avoiding shell compatibility issues.

See also [comment](https://github.com/mtscout6/syntastic-local-eslint.vim/pull/10#issuecomment-280324997) from #10

With this code my vim starts [0.30..0.25 seconds ](https://asciinema.org/a/6fdsdxt6hirs7smld66izji3u) instead of 0.50.
The core functionality [does work](https://asciinema.org/a/9u5wswa8lv2rm53b8s6h7zeys) also.
As a bonus this PR [resolves](http://asciinema.org/a/0cggsykygaebu9g88fxrzw1on) #13 since includes #14.

### CODE REVIEW

**Comment by shofel** [comment]
@mtscout6, could you please provide some feedback on this PR?

**Comment by shofel** [comment]
image

**Comment by oatkiller** [comment]
👍

**Comment by devinmcafee** [comment]
👍  lets get this merged

**Comment by mtscout6** [comment]
Sorry for the delay on this guys. This looks good to me. Thanks!

**Pull request merged**
