### PR TITLE
Support Installation with VimPlugged

### PR DESCRIPTION
**Pull request by pmsorhaindo**
Readme references my fork.

### CODE REVIEW

**Comment by mtscout6** [comment]
cMy originally understanding was that this after folder was getting used to ensure that syntastic was loaded first. However, the variables that are used don't seem to need that requirement. So this looks great to me. Thanks.

**Comment by apfelfabrik** [comment]
This repo (owned by mtscout6) now states in the README to download from pmsorhaindo, which seems weird, as that one is the fork and this is the original.

**Comment by mtscout6** [comment]
Thanks for the pointer about the readme. I'll fix that right away.

**Comment by pmsorhaindo** [comment]
Sorry guys!

**Pull request merged**
